version: "3.9"
services:
  central-server:
    build: ./server
    ports:
      - "5000:5000"
    networks:
      proxy_proxy:
        ipv4_address: 172.28.0.10

  plc1:
    container_name: plc1
    build: ./plc/plc1
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN
    networks:
      proxy_plc:
        ipv4_address: 172.29.0.5
    command: >- 
      sh -c "apt-get update &&
      apt-get install -y iproute2 &&
      ip route del default &&
      ip route add default via 172.29.0.4 &&
      tail -f /dev/null"

  hmi:
    container_name: hmi
    build: ./hmi
    volumes: 
      - ./hmi/scripts:/scripts
    tty: true
    #command: python3 /workdir/server.py
    cap_add:
      - NET_ADMIN
    networks:
      hmi_proxy:
        ipv4_address: 172.27.0.2
    command: >-
      sh -c "ip route del default &&
      ip route add default via 172.27.0.3 &&
      tail -f /dev/null"
      
  #plc's proxy: 
  proxy1:
    container_name: proxy1
    build: ./proxy
    volumes:
    - ./proxy/proxy1:/scripts
    tty: true
    cap_add:
      - NET_ADMIN
    networks:
      proxy_plc:
        ipv4_address: 172.29.0.4
      proxy_proxy:
        ipv4_address: 172.28.0.4
    command: >-
      sh -c "ip route add 172.27.0.0/24 via 172.28.0.3 &&
      cd scripts &&
      tail -f /dev/null"
     #python3 proxy.py"
     
    
  #hmi's proxy:
  proxy2:
    container_name: proxy2
    build: ./proxy
    volumes:
    - ./proxy/proxy2:/scripts
    tty: true
    cap_add:
      - NET_ADMIN
    networks:
      hmi_proxy:
        ipv4_address: 172.27.0.3
      proxy_proxy:
        ipv4_address: 172.28.0.3
    command: >-
      sh -c "ip route add 172.29.0.0/24 via 172.28.0.4 &&
      cd scripts &&
      tail -f /dev/null"
     #python3 proxy.py"
     #tail -f /dev/null
  


networks:
  proxy_proxy:
    driver: bridge
    name: proxy_proxy
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1
  proxy_plc:
    driver: bridge
    name: proxy_plc
    ipam:
      config:
        - subnet: 172.29.0.0/24
          gateway: 172.29.0.1
  hmi_proxy:
    driver: bridge
    name: hmi_proxy
    ipam:
      config:
        - subnet: 127.27.0.0/24
          gateway: 127.27.0.1
    
    
          
